# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class AdvancedVehicleStateMeasurement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAdvancedVehicleStateMeasurement(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AdvancedVehicleStateMeasurement()
        x.Init(buf, n + offset)
        return x

    # AdvancedVehicleStateMeasurement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

# /// the standard data we pack in every message (simulation time, message type, etc.)
# /// with a unique identifier for our vehicle and list of agents colliding with us this frame 
    # AdvancedVehicleStateMeasurement
    def Header(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .AgentStateHeaderData import AgentStateHeaderData
            obj = AgentStateHeaderData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// location of the vehicle body reference point relative to East-North-Up fixed coordinate system origin
    # AdvancedVehicleStateMeasurement
    def Location(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// orientation of the vehicle body relative to East-North-Up fixed coordinate system axes
    # AdvancedVehicleStateMeasurement
    def Orientation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from .Quat4 import Quat4
            obj = Quat4()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// velocity of the vehicle body reference point in body frame coordinate system (i.e. U, V, W)
    # AdvancedVehicleStateMeasurement
    def Velocity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// angular velocity of the vehicle body in body frame coordinate system (i.e. P, Q, R)
    # AdvancedVehicleStateMeasurement
    def AngularVelocity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// acceleration of the vehicle body reference point in body frame coordinate system
    # AdvancedVehicleStateMeasurement
    def Acceleration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// a vector of structures, each giving information on a wheel attached to the vehicle
    # AdvancedVehicleStateMeasurement
    def Wheels(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .AdvancedVehicleWheelsData import AdvancedVehicleWheelsData
            obj = AdvancedVehicleWheelsData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AdvancedVehicleStateMeasurement
    def WheelsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

# /// lights structure
    # AdvancedVehicleStateMeasurement
    def Lights(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = o + self._tab.Pos
            from .VehicleLights import VehicleLights
            obj = VehicleLights()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// honk honk
    # AdvancedVehicleStateMeasurement
    def Horn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos)
        return 0

# /// motion base offset used to calculate eyepoint compensation
    # AdvancedVehicleStateMeasurement
    def PlatformLocation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// motion base orientation used to calculate eyepoint compensation
    # AdvancedVehicleStateMeasurement
    def PlatformOrientation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = o + self._tab.Pos
            from .Quat4 import Quat4
            obj = Quat4()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// data needed by an Unreal-drawn dashboard
    # AdvancedVehicleStateMeasurement
    def Dashboard(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = o + self._tab.Pos
            from .VehicleDashboard import VehicleDashboard
            obj = VehicleDashboard()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// location in a WGS84 (i.e. GPS) frame
    # AdvancedVehicleStateMeasurement
    def LocationWgs84(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Adaptive / smart headlight parameters
    # AdvancedVehicleStateMeasurement
    def AdvancedLights(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .AdvancedVehicleLights import AdvancedVehicleLights
            obj = AdvancedVehicleLights()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def AdvancedVehicleStateMeasurementStart(builder): builder.StartObject(15)
def AdvancedVehicleStateMeasurementAddHeader(builder, header): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)
def AdvancedVehicleStateMeasurementAddLocation(builder, location): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(location), 0)
def AdvancedVehicleStateMeasurementAddOrientation(builder, orientation): builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(orientation), 0)
def AdvancedVehicleStateMeasurementAddVelocity(builder, velocity): builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(velocity), 0)
def AdvancedVehicleStateMeasurementAddAngularVelocity(builder, angularVelocity): builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(angularVelocity), 0)
def AdvancedVehicleStateMeasurementAddAcceleration(builder, acceleration): builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(acceleration), 0)
def AdvancedVehicleStateMeasurementAddWheels(builder, wheels): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(wheels), 0)
def AdvancedVehicleStateMeasurementStartWheelsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def AdvancedVehicleStateMeasurementAddLights(builder, lights): builder.PrependStructSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(lights), 0)
def AdvancedVehicleStateMeasurementAddHorn(builder, horn): builder.PrependBoolSlot(9, horn, 0)
def AdvancedVehicleStateMeasurementAddPlatformLocation(builder, platformLocation): builder.PrependStructSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(platformLocation), 0)
def AdvancedVehicleStateMeasurementAddPlatformOrientation(builder, platformOrientation): builder.PrependStructSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(platformOrientation), 0)
def AdvancedVehicleStateMeasurementAddDashboard(builder, dashboard): builder.PrependStructSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(dashboard), 0)
def AdvancedVehicleStateMeasurementAddLocationWgs84(builder, locationWgs84): builder.PrependStructSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(locationWgs84), 0)
def AdvancedVehicleStateMeasurementAddAdvancedLights(builder, advancedLights): builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(advancedLights), 0)
def AdvancedVehicleStateMeasurementEnd(builder): return builder.EndObject()
