# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class AdvancedVehicleLights(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAdvancedVehicleLights(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AdvancedVehicleLights()
        x.Init(buf, n + offset)
        return x

    # AdvancedVehicleLights
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

# /// Pitch of left high beam headlight
    # AdvancedVehicleLights
    def HighBeamLeftPitchDegrees(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Yaw of left high beam headlight
    # AdvancedVehicleLights
    def HighBeamLeftYawDegrees(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Pitch of right high beam headlight
    # AdvancedVehicleLights
    def HighBeamRightPitchDegrees(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Yaw of right high beam headlight
    # AdvancedVehicleLights
    def HighBeamRightYawDegrees(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Pitch of left low beam headlight
    # AdvancedVehicleLights
    def LowBeamLeftPitchDegrees(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Yaw of left low beam headlight
    # AdvancedVehicleLights
    def LowBeamLeftYawDegrees(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Pitch of right low beam headlight
    # AdvancedVehicleLights
    def LowBeamRightPitchDegrees(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Yaw of right low beam headlight
    # AdvancedVehicleLights
    def LowBeamRightYawDegrees(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def AdvancedVehicleLightsStart(builder): builder.StartObject(8)
def AdvancedVehicleLightsAddHighBeamLeftPitchDegrees(builder, highBeamLeftPitchDegrees): builder.PrependFloat32Slot(0, highBeamLeftPitchDegrees, 0.0)
def AdvancedVehicleLightsAddHighBeamLeftYawDegrees(builder, highBeamLeftYawDegrees): builder.PrependFloat32Slot(1, highBeamLeftYawDegrees, 0.0)
def AdvancedVehicleLightsAddHighBeamRightPitchDegrees(builder, highBeamRightPitchDegrees): builder.PrependFloat32Slot(2, highBeamRightPitchDegrees, 0.0)
def AdvancedVehicleLightsAddHighBeamRightYawDegrees(builder, highBeamRightYawDegrees): builder.PrependFloat32Slot(3, highBeamRightYawDegrees, 0.0)
def AdvancedVehicleLightsAddLowBeamLeftPitchDegrees(builder, lowBeamLeftPitchDegrees): builder.PrependFloat32Slot(4, lowBeamLeftPitchDegrees, 0.0)
def AdvancedVehicleLightsAddLowBeamLeftYawDegrees(builder, lowBeamLeftYawDegrees): builder.PrependFloat32Slot(5, lowBeamLeftYawDegrees, 0.0)
def AdvancedVehicleLightsAddLowBeamRightPitchDegrees(builder, lowBeamRightPitchDegrees): builder.PrependFloat32Slot(6, lowBeamRightPitchDegrees, 0.0)
def AdvancedVehicleLightsAddLowBeamRightYawDegrees(builder, lowBeamRightYawDegrees): builder.PrependFloat32Slot(7, lowBeamRightYawDegrees, 0.0)
def AdvancedVehicleLightsEnd(builder): return builder.EndObject()
