# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class AdvancedVehicleWheelsData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAdvancedVehicleWheelsData(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AdvancedVehicleWheelsData()
        x.Init(buf, n + offset)
        return x

    # AdvancedVehicleWheelsData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

# /// which wheel is this?
    # AdvancedVehicleWheelsData
    def Index(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

# /// the surface type that the tire surface is in contact with
    # AdvancedVehicleWheelsData
    def ContactMaterialName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

# /// location of the wheel reference point relative to vehicle body coordinate system origin (????? confirm with VI-Grade)
    # AdvancedVehicleWheelsData
    def Location(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// orientation of the wheel relative to vehicle body coordinate system axes (????? confirm with VI-Grade)
    # AdvancedVehicleWheelsData
    def Orientation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from .Quat4 import Quat4
            obj = Quat4()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// velocity of the wheel in wheel frame coordinate system (????? confirm with VI-Grade)
    # AdvancedVehicleWheelsData
    def Velocity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// angular velocity of the wheel in wheel frame coordinate system (????? confirm with VI-Grade)
    # AdvancedVehicleWheelsData
    def AngularVelocity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def AdvancedVehicleWheelsDataStart(builder): builder.StartObject(6)
def AdvancedVehicleWheelsDataAddIndex(builder, index): builder.PrependInt8Slot(0, index, 0)
def AdvancedVehicleWheelsDataAddContactMaterialName(builder, contactMaterialName): builder.PrependInt8Slot(1, contactMaterialName, 0)
def AdvancedVehicleWheelsDataAddLocation(builder, location): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(location), 0)
def AdvancedVehicleWheelsDataAddOrientation(builder, orientation): builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(orientation), 0)
def AdvancedVehicleWheelsDataAddVelocity(builder, velocity): builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(velocity), 0)
def AdvancedVehicleWheelsDataAddAngularVelocity(builder, angularVelocity): builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(angularVelocity), 0)
def AdvancedVehicleWheelsDataEnd(builder): return builder.EndObject()
