# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class AgentStateHeaderData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAgentStateHeaderData(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AgentStateHeaderData()
        x.Init(buf, n + offset)
        return x

    # AgentStateHeaderData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

# /// Simulation time (s)
    # AgentStateHeaderData
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

# /// Increment for each message
    # AgentStateHeaderData
    def SequenceNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

# /// Type tag indicating the message sender
    # AgentStateHeaderData
    def Source(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

# /// UUID of this agent
    # AgentStateHeaderData
    def Uuid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from .UUID import UUID
            obj = UUID()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Other agents colliding with this agent, and their semantic tag
    # AgentStateHeaderData
    def Collisions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 20
            from .IDTag import IDTag
            obj = IDTag()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AgentStateHeaderData
    def CollisionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def AgentStateHeaderDataStart(builder): builder.StartObject(5)
def AgentStateHeaderDataAddTimestamp(builder, timestamp): builder.PrependFloat64Slot(0, timestamp, 0.0)
def AgentStateHeaderDataAddSequenceNo(builder, sequenceNo): builder.PrependUint32Slot(1, sequenceNo, 0)
def AgentStateHeaderDataAddSource(builder, source): builder.PrependInt8Slot(2, source, 0)
def AgentStateHeaderDataAddUuid(builder, uuid): builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(uuid), 0)
def AgentStateHeaderDataAddCollisions(builder, collisions): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(collisions), 0)
def AgentStateHeaderDataStartCollisionsVector(builder, numElems): return builder.StartVector(20, numElems, 4)
def AgentStateHeaderDataEnd(builder): return builder.EndObject()
