# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

# /// Used by the SDK to respond to advancement of simulation time
class ControlToProxyReply(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsControlToProxyReply(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ControlToProxyReply()
        x.Init(buf, n + offset)
        return x

    # ControlToProxyReply
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ControlToProxyReply
    def Reply(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ControlToProxyReply
    def Time(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # ControlToProxyReply
    def UnupdatedNpcCars(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ControlToProxyReplyStart(builder): builder.StartObject(3)
def ControlToProxyReplyAddReply(builder, reply): builder.PrependInt8Slot(0, reply, 0)
def ControlToProxyReplyAddTime(builder, time): builder.PrependFloat64Slot(1, time, 0.0)
def ControlToProxyReplyAddUnupdatedNpcCars(builder, unupdatedNpcCars): builder.PrependInt32Slot(2, unupdatedNpcCars, 0)
def ControlToProxyReplyEnd(builder): return builder.EndObject()
