# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class DepthImageMeasurement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDepthImageMeasurement(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DepthImageMeasurement()
        x.Init(buf, n + offset)
        return x

    # DepthImageMeasurement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DepthImageMeasurement
    def Header(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .HeaderData import HeaderData
            obj = HeaderData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Raw pixels for the image
    # DepthImageMeasurement
    def Pixels(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from .DepthPixel import DepthPixel
            obj = DepthPixel()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DepthImageMeasurement
    def PixelsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

# /// Currently unused
    # DepthImageMeasurement
    def Encoding(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

# /// Image width in pixels
    # DepthImageMeasurement
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

# /// Image height in pixels
    # DepthImageMeasurement
    def Height(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def DepthImageMeasurementStart(builder): builder.StartObject(5)
def DepthImageMeasurementAddHeader(builder, header): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)
def DepthImageMeasurementAddPixels(builder, pixels): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(pixels), 0)
def DepthImageMeasurementStartPixelsVector(builder, numElems): return builder.StartVector(8, numElems, 4)
def DepthImageMeasurementAddEncoding(builder, encoding): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(encoding), 0)
def DepthImageMeasurementAddWidth(builder, width): builder.PrependInt32Slot(3, width, 0)
def DepthImageMeasurementAddHeight(builder, height): builder.PrependInt32Slot(4, height, 0)
def DepthImageMeasurementEnd(builder): return builder.EndObject()
