# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class DepthPixel(object):
    __slots__ = ['_tab']

    # DepthPixel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

# /// Distance in meters. Infinity if the distance exceeds the sensor's maximum range.
    # DepthPixel
    def Depth(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
# /// Reflected light intensity
    # DepthPixel
    def Intensity(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateDepthPixel(builder, depth, intensity):
    builder.Prep(4, 8)
    builder.PrependFloat32(intensity)
    builder.PrependFloat32(depth)
    return builder.Offset()
