# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

# /// Single common root for all engine services, containing one type per message
# /// (used by both request and reply messages)
class EngineService(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsEngineService(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EngineService()
        x.Init(buf, n + offset)
        return x

    # EngineService
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EngineService
    def ServiceType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EngineService
    def Service(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def EngineServiceStart(builder): builder.StartObject(2)
def EngineServiceAddServiceType(builder, serviceType): builder.PrependUint8Slot(0, serviceType, 0)
def EngineServiceAddService(builder, service): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(service), 0)
def EngineServiceEnd(builder): return builder.EndObject()
