# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

class EngineServiceType(object):
    NONE = 0
    SnapToGround = 1
    SimStateRequest = 2
    SimStateReply = 3

