# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class EnvironmentTime(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsEnvironmentTime(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EnvironmentTime()
        x.Init(buf, n + offset)
        return x

    # EnvironmentTime
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EnvironmentTime
    def Year(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EnvironmentTime
    def Month(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EnvironmentTime
    def Day(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EnvironmentTime
    def SecondsSinceMidnight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Sunrise time in seconds since midnight
    # EnvironmentTime
    def Sunrise(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Sunset time in seconds since midnight
    # EnvironmentTime
    def Sunset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def EnvironmentTimeStart(builder): builder.StartObject(6)
def EnvironmentTimeAddYear(builder, year): builder.PrependInt32Slot(0, year, 0)
def EnvironmentTimeAddMonth(builder, month): builder.PrependInt32Slot(1, month, 0)
def EnvironmentTimeAddDay(builder, day): builder.PrependInt32Slot(2, day, 0)
def EnvironmentTimeAddSecondsSinceMidnight(builder, secondsSinceMidnight): builder.PrependFloat32Slot(3, secondsSinceMidnight, 0.0)
def EnvironmentTimeAddSunrise(builder, sunrise): builder.PrependFloat32Slot(4, sunrise, 0.0)
def EnvironmentTimeAddSunset(builder, sunset): builder.PrependFloat32Slot(5, sunset, 0.0)
def EnvironmentTimeEnd(builder): return builder.EndObject()
