# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class EnvironmentWeather(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsEnvironmentWeather(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EnvironmentWeather()
        x.Init(buf, n + offset)
        return x

    # EnvironmentWeather
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

# /// Amount of cloud cover [0.0, 1.0]
    # EnvironmentWeather
    def Overcast(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Rain intensity [0.0, 1.0]
    # EnvironmentWeather
    def Rain(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Wetness of the roads (reflectivity) [0.0, 1.0]
    # EnvironmentWeather
    def Wetness(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Thickness of fog [0.0, 1.0]
    # EnvironmentWeather
    def Fog(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def EnvironmentWeatherStart(builder): builder.StartObject(4)
def EnvironmentWeatherAddOvercast(builder, overcast): builder.PrependFloat32Slot(0, overcast, 0.0)
def EnvironmentWeatherAddRain(builder, rain): builder.PrependFloat32Slot(1, rain, 0.0)
def EnvironmentWeatherAddWetness(builder, wetness): builder.PrependFloat32Slot(2, wetness, 0.0)
def EnvironmentWeatherAddFog(builder, fog): builder.PrependFloat32Slot(3, fog, 0.0)
def EnvironmentWeatherEnd(builder): return builder.EndObject()
