# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class GroupedStateMeasurement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGroupedStateMeasurement(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GroupedStateMeasurement()
        x.Init(buf, n + offset)
        return x

    # GroupedStateMeasurement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GroupedStateMeasurement
    def Header(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .HeaderData import HeaderData
            obj = HeaderData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GroupedStateMeasurement
    def KinematicStates(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .KinematicStateMeasurement import KinematicStateMeasurement
            obj = KinematicStateMeasurement()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GroupedStateMeasurement
    def KinematicStatesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GroupedStateMeasurement
    def PedestrianStates(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .PedestrianStateMeasurement import PedestrianStateMeasurement
            obj = PedestrianStateMeasurement()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GroupedStateMeasurement
    def PedestrianStatesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GroupedStateMeasurement
    def PhysicsVehicleStates(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .PhysicsVehicleStateMeasurement import PhysicsVehicleStateMeasurement
            obj = PhysicsVehicleStateMeasurement()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GroupedStateMeasurement
    def PhysicsVehicleStatesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GroupedStateMeasurement
    def AdvancedVehicleStates(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .AdvancedVehicleStateMeasurement import AdvancedVehicleStateMeasurement
            obj = AdvancedVehicleStateMeasurement()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GroupedStateMeasurement
    def AdvancedVehicleStatesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

# /// Date and time. This field is only populated when a time change occurs
    # GroupedStateMeasurement
    def EnvironmentTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .EnvironmentTime import EnvironmentTime
            obj = EnvironmentTime()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Weather conditions. This field is only populated when a weather change occurs
    # GroupedStateMeasurement
    def EnvironmentWeather(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .EnvironmentWeather import EnvironmentWeather
            obj = EnvironmentWeather()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Current state of all traffic signals. NOTE: This is expected to change soon
    # GroupedStateMeasurement
    def TrafficSignals(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .TrafficSignals import TrafficSignals
            obj = TrafficSignals()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Any active trigger events being fired this time step, otherwise empty
    # GroupedStateMeasurement
    def TriggerEvents(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .TriggerEvent import TriggerEvent
            obj = TriggerEvent()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GroupedStateMeasurement
    def TriggerEventsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

# /// PhysicsVehicleActuationCommand with VehicleControlIntent from MultiAgent
    # GroupedStateMeasurement
    def VehicleActuationCommands(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .PhysicsVehicleActuationCommandBuffer import PhysicsVehicleActuationCommandBuffer
            obj = PhysicsVehicleActuationCommandBuffer()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GroupedStateMeasurement
    def VehicleActuationCommandsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

# /// Dynamic state of each trigger
    # GroupedStateMeasurement
    def TriggerStates(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .TriggerState import TriggerState
            obj = TriggerState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GroupedStateMeasurement
    def TriggerStatesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

# /// Any active interaction events being fired this step, otherwise empty
    # GroupedStateMeasurement
    def StateEvents(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .StateEvent import StateEvent
            obj = StateEvent()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GroupedStateMeasurement
    def StateEventsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def GroupedStateMeasurementStart(builder): builder.StartObject(12)
def GroupedStateMeasurementAddHeader(builder, header): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)
def GroupedStateMeasurementAddKinematicStates(builder, kinematicStates): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(kinematicStates), 0)
def GroupedStateMeasurementStartKinematicStatesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def GroupedStateMeasurementAddPedestrianStates(builder, pedestrianStates): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(pedestrianStates), 0)
def GroupedStateMeasurementStartPedestrianStatesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def GroupedStateMeasurementAddPhysicsVehicleStates(builder, physicsVehicleStates): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(physicsVehicleStates), 0)
def GroupedStateMeasurementStartPhysicsVehicleStatesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def GroupedStateMeasurementAddAdvancedVehicleStates(builder, advancedVehicleStates): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(advancedVehicleStates), 0)
def GroupedStateMeasurementStartAdvancedVehicleStatesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def GroupedStateMeasurementAddEnvironmentTime(builder, environmentTime): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(environmentTime), 0)
def GroupedStateMeasurementAddEnvironmentWeather(builder, environmentWeather): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(environmentWeather), 0)
def GroupedStateMeasurementAddTrafficSignals(builder, trafficSignals): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(trafficSignals), 0)
def GroupedStateMeasurementAddTriggerEvents(builder, triggerEvents): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(triggerEvents), 0)
def GroupedStateMeasurementStartTriggerEventsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def GroupedStateMeasurementAddVehicleActuationCommands(builder, vehicleActuationCommands): builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(vehicleActuationCommands), 0)
def GroupedStateMeasurementStartVehicleActuationCommandsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def GroupedStateMeasurementAddTriggerStates(builder, triggerStates): builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(triggerStates), 0)
def GroupedStateMeasurementStartTriggerStatesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def GroupedStateMeasurementAddStateEvents(builder, stateEvents): builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(stateEvents), 0)
def GroupedStateMeasurementStartStateEventsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def GroupedStateMeasurementEnd(builder): return builder.EndObject()
