# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class HeaderData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsHeaderData(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HeaderData()
        x.Init(buf, n + offset)
        return x

    # HeaderData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HeaderData
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # HeaderData
    def SequenceNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # HeaderData
    def Source(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def HeaderDataStart(builder): builder.StartObject(3)
def HeaderDataAddTimestamp(builder, timestamp): builder.PrependFloat64Slot(0, timestamp, 0.0)
def HeaderDataAddSequenceNo(builder, sequenceNo): builder.PrependUint32Slot(1, sequenceNo, 0)
def HeaderDataAddSource(builder, source): builder.PrependInt8Slot(2, source, 0)
def HeaderDataEnd(builder): return builder.EndObject()
