# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class HeaderRoot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsHeaderRoot(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HeaderRoot()
        x.Init(buf, n + offset)
        return x

    # HeaderRoot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HeaderRoot
    def Header(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .HeaderData import HeaderData
            obj = HeaderData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def HeaderRootStart(builder): builder.StartObject(1)
def HeaderRootAddHeader(builder, header): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)
def HeaderRootEnd(builder): return builder.EndObject()
