# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class IDTag(object):
    __slots__ = ['_tab']

    # IDTag
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

# /// Agent UUID
    # IDTag
    def Uuid(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

# /// Semantic tag
    # IDTag
    def Tag(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))

def CreateIDTag(builder, uuid_a, uuid_b, uuid_c, uuid_d, tag):
    builder.Prep(4, 20)
    builder.PrependUint32(tag)
    builder.Prep(4, 16)
    builder.PrependUint32(uuid_d)
    builder.PrependUint32(uuid_c)
    builder.PrependUint32(uuid_b)
    builder.PrependUint32(uuid_a)
    return builder.Offset()
