# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

class ImageEncoding(object):
# /// 8 bits per pixel grayscale luminance
# /// Encoded using a variant of the NTSC-style R * 0.3 + G * 0.59 + B * 0.11
# /// Specifically, uint8(R * 5 + G * 9 + B * 2) >> 4
    MONO8 = 0
# /// 8-bit bayer pattern image
# /// Odd rows alternate between blue and green values
# /// Even rows alternate between green and red values
    BAYER_RGGB8 = 1
# /// Plain 8-bit color imagery
    RGB8 = 2

