# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class KinematicActuationCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsKinematicActuationCommand(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KinematicActuationCommand()
        x.Init(buf, n + offset)
        return x

    # KinematicActuationCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # KinematicActuationCommand
    def Header(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .HeaderData import HeaderData
            obj = HeaderData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KinematicActuationCommand
    def Uuid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from .UUID import UUID
            obj = UUID()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// World space offset (m) from the East-North-Up origin
    # KinematicActuationCommand
    def Location(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// World space rotation (rad) relative to East-North-Up axis
    # KinematicActuationCommand
    def Orientation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from .Quat4 import Quat4
            obj = Quat4()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Object space velocity (m/s)
    # KinematicActuationCommand
    def Velocity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Object space angular velocity (rad/s)
    # KinematicActuationCommand
    def AngularVelocity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def KinematicActuationCommandStart(builder): builder.StartObject(6)
def KinematicActuationCommandAddHeader(builder, header): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)
def KinematicActuationCommandAddUuid(builder, uuid): builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(uuid), 0)
def KinematicActuationCommandAddLocation(builder, location): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(location), 0)
def KinematicActuationCommandAddOrientation(builder, orientation): builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(orientation), 0)
def KinematicActuationCommandAddVelocity(builder, velocity): builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(velocity), 0)
def KinematicActuationCommandAddAngularVelocity(builder, angularVelocity): builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(angularVelocity), 0)
def KinematicActuationCommandEnd(builder): return builder.EndObject()
