# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class LaneMarking(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsLaneMarking(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LaneMarking()
        x.Init(buf, n + offset)
        return x

    # LaneMarking
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

# /// In sensor space, first point has smallest x
    # LaneMarking
    def Points(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LaneMarking
    def PointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

# /// Define sections using points array
    # LaneMarking
    def Sections(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 24
            from .LaneMarkingSection import LaneMarkingSection
            obj = LaneMarkingSection()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LaneMarking
    def SectionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

# /// Polynomial coefficients (2D)
# /// Use with x value of first and last point
    # LaneMarking
    def C0(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LaneMarking
    def C1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LaneMarking
    def C2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LaneMarking
    def C3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def LaneMarkingStart(builder): builder.StartObject(6)
def LaneMarkingAddPoints(builder, points): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(points), 0)
def LaneMarkingStartPointsVector(builder, numElems): return builder.StartVector(12, numElems, 4)
def LaneMarkingAddSections(builder, sections): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(sections), 0)
def LaneMarkingStartSectionsVector(builder, numElems): return builder.StartVector(24, numElems, 4)
def LaneMarkingAddC0(builder, c0): builder.PrependFloat32Slot(2, c0, 0.0)
def LaneMarkingAddC1(builder, c1): builder.PrependFloat32Slot(3, c1, 0.0)
def LaneMarkingAddC2(builder, c2): builder.PrependFloat32Slot(4, c2, 0.0)
def LaneMarkingAddC3(builder, c3): builder.PrependFloat32Slot(5, c3, 0.0)
def LaneMarkingEnd(builder): return builder.EndObject()
