# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class LaneMarkingSection(object):
    __slots__ = ['_tab']

    # LaneMarkingSection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

# /// Index into LaneMarking::points for start of each section
    # LaneMarkingSection
    def Index(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
# /// UUID and tag for each section
    # LaneMarkingSection
    def IdTag(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 4)
        return obj


def CreateLaneMarkingSection(builder, index, id_tag_uuid_a, id_tag_uuid_b, id_tag_uuid_c, id_tag_uuid_d, id_tag_tag):
    builder.Prep(4, 24)
    builder.Prep(4, 20)
    builder.PrependUint32(id_tag_tag)
    builder.Prep(4, 16)
    builder.PrependUint32(id_tag_uuid_d)
    builder.PrependUint32(id_tag_uuid_c)
    builder.PrependUint32(id_tag_uuid_b)
    builder.PrependUint32(id_tag_uuid_a)
    builder.PrependInt32(index)
    return builder.Offset()
