# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class LaserscanMeasurement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsLaserscanMeasurement(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LaserscanMeasurement()
        x.Init(buf, n + offset)
        return x

    # LaserscanMeasurement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LaserscanMeasurement
    def Header(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .HeaderData import HeaderData
            obj = HeaderData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Array of values for each sweep angle defined in the sensor profile
# /// Each value represents distance in meters, or infinity if nothing was hit
    # LaserscanMeasurement
    def Ranges(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # LaserscanMeasurement
    def RangesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # LaserscanMeasurement
    def RangesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def LaserscanMeasurementStart(builder): builder.StartObject(2)
def LaserscanMeasurementAddHeader(builder, header): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)
def LaserscanMeasurementAddRanges(builder, ranges): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(ranges), 0)
def LaserscanMeasurementStartRangesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def LaserscanMeasurementEnd(builder): return builder.EndObject()
