# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

# /// point feature data type with bounding box wrt sensor space
class ObjData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsObjData(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ObjData()
        x.Init(buf, n + offset)
        return x

    # ObjData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

# /// UUID and gameplay tag
    # ObjData
    def IdTag(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .IDTag import IDTag
            obj = IDTag()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ObjData
    def Rotation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from .Quat4 import Quat4
            obj = Quat4()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Center of object's bounding box
    # ObjData
    def Center(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Depth, width, height of bounding box (x, y, z)
    # ObjData
    def Size(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ObjDataStart(builder): builder.StartObject(4)
def ObjDataAddIdTag(builder, idTag): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(idTag), 0)
def ObjDataAddRotation(builder, rotation): builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(rotation), 0)
def ObjDataAddCenter(builder, center): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(center), 0)
def ObjDataAddSize(builder, size): builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(size), 0)
def ObjDataEnd(builder): return builder.EndObject()
