# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class PedestrianStateMeasurement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPedestrianStateMeasurement(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PedestrianStateMeasurement()
        x.Init(buf, n + offset)
        return x

    # PedestrianStateMeasurement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PedestrianStateMeasurement
    def Header(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .AgentStateHeaderData import AgentStateHeaderData
            obj = AgentStateHeaderData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// World space offset (m) from the East-North-Up origin
    # PedestrianStateMeasurement
    def Location(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// World space rotation (rad) relative to East-North-Up axis
    # PedestrianStateMeasurement
    def Orientation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from .Quat4 import Quat4
            obj = Quat4()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Object space velocity (m/s)
    # PedestrianStateMeasurement
    def Velocity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Object space angular velocity (rad/s)
    # PedestrianStateMeasurement
    def AngularVelocity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// GNSS location in WGS84 datum
    # PedestrianStateMeasurement
    def LocationWgs84(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def PedestrianStateMeasurementStart(builder): builder.StartObject(7)
def PedestrianStateMeasurementAddHeader(builder, header): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)
def PedestrianStateMeasurementAddLocation(builder, location): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(location), 0)
def PedestrianStateMeasurementAddOrientation(builder, orientation): builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(orientation), 0)
def PedestrianStateMeasurementAddVelocity(builder, velocity): builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(velocity), 0)
def PedestrianStateMeasurementAddAngularVelocity(builder, angularVelocity): builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(angularVelocity), 0)
def PedestrianStateMeasurementAddLocationWgs84(builder, locationWgs84): builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(locationWgs84), 0)
def PedestrianStateMeasurementEnd(builder): return builder.EndObject()
