# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class PedestrianActuationCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPedestrianActuationCommand(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PedestrianActuationCommand()
        x.Init(buf, n + offset)
        return x

    # PedestrianActuationCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PedestrianActuationCommand
    def Header(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .HeaderData import HeaderData
            obj = HeaderData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PedestrianActuationCommand
    def Uuid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from .UUID import UUID
            obj = UUID()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// World space offset (m) from the East-North-Up origin
    # PedestrianActuationCommand
    def Location(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// World space rotation (rad) relative to East-North-Up axis
    # PedestrianActuationCommand
    def Orientation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from .Quat4 import Quat4
            obj = Quat4()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Object space velocity (m/s)
    # PedestrianActuationCommand
    def Velocity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Object space angular velocity (rad/s)
    # PedestrianActuationCommand
    def AngularVelocity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Set when the agent wants to immediately jump elsewhere
    # PedestrianActuationCommand
    def TeleportRequest(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            from .TeleportRequest import TeleportRequest
            obj = TeleportRequest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def PedestrianActuationCommandStart(builder): builder.StartObject(7)
def PedestrianActuationCommandAddHeader(builder, header): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)
def PedestrianActuationCommandAddUuid(builder, uuid): builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(uuid), 0)
def PedestrianActuationCommandAddLocation(builder, location): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(location), 0)
def PedestrianActuationCommandAddOrientation(builder, orientation): builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(orientation), 0)
def PedestrianActuationCommandAddVelocity(builder, velocity): builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(velocity), 0)
def PedestrianActuationCommandAddAngularVelocity(builder, angularVelocity): builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(angularVelocity), 0)
def PedestrianActuationCommandAddTeleportRequest(builder, teleportRequest): builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(teleportRequest), 0)
def PedestrianActuationCommandEnd(builder): return builder.EndObject()
