# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class PhysicsVehicleActuationCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPhysicsVehicleActuationCommand(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PhysicsVehicleActuationCommand()
        x.Init(buf, n + offset)
        return x

    # PhysicsVehicleActuationCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PhysicsVehicleActuationCommand
    def Header(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .HeaderData import HeaderData
            obj = HeaderData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PhysicsVehicleActuationCommand
    def Uuid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from .UUID import UUID
            obj = UUID()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Steering (deg) [-45.0, 45.0] where negative values indicate a right turn
    # PhysicsVehicleActuationCommand
    def SteeringDegrees(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Amount of throttle [0.0, 1.0] where 1.0 is wide open throttle
    # PhysicsVehicleActuationCommand
    def NormalizedThrottle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Amount of braking [0.0, 1.0] where 1.0 is full brakes
    # PhysicsVehicleActuationCommand
    def NormalizedBrake(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Shift to reverse gear
    # PhysicsVehicleActuationCommand
    def ReverseGearRequest(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos)
        return 0

# /// Amount of hand brake [0.0, 1.0]
    # PhysicsVehicleActuationCommand
    def NormalizedHandbrake(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// State of each type of light (@see common.fbs)
    # PhysicsVehicleActuationCommand
    def Lights(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            from .VehicleLights import VehicleLights
            obj = VehicleLights()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// If honking the horn
    # PhysicsVehicleActuationCommand
    def Horn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos)
        return 0

# /// Set when the agent wants to immediately jump elsewhere
    # PhysicsVehicleActuationCommand
    def TeleportRequest(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = o + self._tab.Pos
            from .TeleportRequest import TeleportRequest
            obj = TeleportRequest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Selected internal state the agent used to compute the above throttle/brake/steering.
# /// This is populated in the GroupedStateMeasurement message for controlled agents with
# /// ai_controlled set to true.
# ///
# /// NOTE: Currently unstable, but may be useful for experiments with autonomous vehicle guidance.
    # PhysicsVehicleActuationCommand
    def VehicleControlIntent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .VehicleControlIntent import VehicleControlIntent
            obj = VehicleControlIntent()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Adaptive / smart headlight parameters
    # PhysicsVehicleActuationCommand
    def AdvancedLights(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .AdvancedVehicleLights import AdvancedVehicleLights
            obj = AdvancedVehicleLights()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Control automatic vehicle features
    # PhysicsVehicleActuationCommand
    def Features(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .VehicleFeatures import VehicleFeatures
            obj = VehicleFeatures()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def PhysicsVehicleActuationCommandStart(builder): builder.StartObject(13)
def PhysicsVehicleActuationCommandAddHeader(builder, header): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)
def PhysicsVehicleActuationCommandAddUuid(builder, uuid): builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(uuid), 0)
def PhysicsVehicleActuationCommandAddSteeringDegrees(builder, steeringDegrees): builder.PrependFloat32Slot(2, steeringDegrees, 0.0)
def PhysicsVehicleActuationCommandAddNormalizedThrottle(builder, normalizedThrottle): builder.PrependFloat32Slot(3, normalizedThrottle, 0.0)
def PhysicsVehicleActuationCommandAddNormalizedBrake(builder, normalizedBrake): builder.PrependFloat32Slot(4, normalizedBrake, 0.0)
def PhysicsVehicleActuationCommandAddReverseGearRequest(builder, reverseGearRequest): builder.PrependBoolSlot(5, reverseGearRequest, 0)
def PhysicsVehicleActuationCommandAddNormalizedHandbrake(builder, normalizedHandbrake): builder.PrependFloat32Slot(6, normalizedHandbrake, 0.0)
def PhysicsVehicleActuationCommandAddLights(builder, lights): builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(lights), 0)
def PhysicsVehicleActuationCommandAddHorn(builder, horn): builder.PrependBoolSlot(8, horn, 0)
def PhysicsVehicleActuationCommandAddTeleportRequest(builder, teleportRequest): builder.PrependStructSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(teleportRequest), 0)
def PhysicsVehicleActuationCommandAddVehicleControlIntent(builder, vehicleControlIntent): builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(vehicleControlIntent), 0)
def PhysicsVehicleActuationCommandAddAdvancedLights(builder, advancedLights): builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(advancedLights), 0)
def PhysicsVehicleActuationCommandAddFeatures(builder, features): builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(features), 0)
def PhysicsVehicleActuationCommandEnd(builder): return builder.EndObject()
