# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class PhysicsVehicleStateMeasurement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPhysicsVehicleStateMeasurement(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PhysicsVehicleStateMeasurement()
        x.Init(buf, n + offset)
        return x

    # PhysicsVehicleStateMeasurement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PhysicsVehicleStateMeasurement
    def Header(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .AgentStateHeaderData import AgentStateHeaderData
            obj = AgentStateHeaderData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// World space offset (m) from the East-North-Up origin
    # PhysicsVehicleStateMeasurement
    def Location(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// World space rotation (rad) relative to East-North-Up axis
    # PhysicsVehicleStateMeasurement
    def Orientation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from .Quat4 import Quat4
            obj = Quat4()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Object space velocity (m/s)
    # PhysicsVehicleStateMeasurement
    def Velocity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Object space angular velocity (rad/s)
    # PhysicsVehicleStateMeasurement
    def AngularVelocity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Object space acceleration (m/s^2)
    # PhysicsVehicleStateMeasurement
    def Acceleration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Transmission gear
    # PhysicsVehicleStateMeasurement
    def Gear(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

# /// Rotation rate of engine (RPM)
    # PhysicsVehicleStateMeasurement
    def EngineSpeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Individual wheel state
    # PhysicsVehicleStateMeasurement
    def Wheels(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .PhysicsVehicleWheelsData import PhysicsVehicleWheelsData
            obj = PhysicsVehicleWheelsData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PhysicsVehicleStateMeasurement
    def WheelsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

# /// GNSS location in WGS84 datum
    # PhysicsVehicleStateMeasurement
    def LocationWgs84(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Drag force (in X)
    # PhysicsVehicleStateMeasurement
    def DragForce(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Down force (in Z)
    # PhysicsVehicleStateMeasurement
    def DownForce(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Max engine speed (rpm)
    # PhysicsVehicleStateMeasurement
    def MaxEngineRpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Max engine torque
    # PhysicsVehicleStateMeasurement
    def MaxEngineTorque(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def PhysicsVehicleStateMeasurementStart(builder): builder.StartObject(15)
def PhysicsVehicleStateMeasurementAddHeader(builder, header): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)
def PhysicsVehicleStateMeasurementAddLocation(builder, location): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(location), 0)
def PhysicsVehicleStateMeasurementAddOrientation(builder, orientation): builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(orientation), 0)
def PhysicsVehicleStateMeasurementAddVelocity(builder, velocity): builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(velocity), 0)
def PhysicsVehicleStateMeasurementAddAngularVelocity(builder, angularVelocity): builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(angularVelocity), 0)
def PhysicsVehicleStateMeasurementAddAcceleration(builder, acceleration): builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(acceleration), 0)
def PhysicsVehicleStateMeasurementAddGear(builder, gear): builder.PrependInt32Slot(7, gear, 0)
def PhysicsVehicleStateMeasurementAddEngineSpeed(builder, engineSpeed): builder.PrependFloat32Slot(8, engineSpeed, 0.0)
def PhysicsVehicleStateMeasurementAddWheels(builder, wheels): builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(wheels), 0)
def PhysicsVehicleStateMeasurementStartWheelsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def PhysicsVehicleStateMeasurementAddLocationWgs84(builder, locationWgs84): builder.PrependStructSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(locationWgs84), 0)
def PhysicsVehicleStateMeasurementAddDragForce(builder, dragForce): builder.PrependFloat32Slot(11, dragForce, 0.0)
def PhysicsVehicleStateMeasurementAddDownForce(builder, downForce): builder.PrependFloat32Slot(12, downForce, 0.0)
def PhysicsVehicleStateMeasurementAddMaxEngineRpm(builder, maxEngineRpm): builder.PrependFloat32Slot(13, maxEngineRpm, 0.0)
def PhysicsVehicleStateMeasurementAddMaxEngineTorque(builder, maxEngineTorque): builder.PrependFloat32Slot(14, maxEngineTorque, 0.0)
def PhysicsVehicleStateMeasurementEnd(builder): return builder.EndObject()
