# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class PhysicsVehicleWheelsData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPhysicsVehicleWheelsData(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PhysicsVehicleWheelsData()
        x.Init(buf, n + offset)
        return x

    # PhysicsVehicleWheelsData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

# /// Wheel position on vehicle
    # PhysicsVehicleWheelsData
    def Index(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

# /// Amount of longitudinal slip
    # PhysicsVehicleWheelsData
    def LongSlip(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Amount of lateral slip
    # PhysicsVehicleWheelsData
    def LatSlip(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Force the tire experiences at rest divided by what it's experiencing now
    # PhysicsVehicleWheelsData
    def NormalizedTireLoad(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Torque force
    # PhysicsVehicleWheelsData
    def Torque(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Longitudinal force applied by the wheel to the chassis
    # PhysicsVehicleWheelsData
    def LongForce(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Lateral force applied by the wheel to the chassis
    # PhysicsVehicleWheelsData
    def LatForce(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// World space location of the wheel
    # PhysicsVehicleWheelsData
    def WheelLocation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// World space velocity of the wheel
    # PhysicsVehicleWheelsData
    def WheelVelocity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Steering angle (deg)
    # PhysicsVehicleWheelsData
    def SteerAngle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Angle about the rolling axis (deg)
    # PhysicsVehicleWheelsData
    def RotationAngle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Material type underneath the wheel
    # PhysicsVehicleWheelsData
    def ContactMaterialName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

# /// Max brake torque
    # PhysicsVehicleWheelsData
    def MaxBrakeTorque(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def PhysicsVehicleWheelsDataStart(builder): builder.StartObject(13)
def PhysicsVehicleWheelsDataAddIndex(builder, index): builder.PrependInt8Slot(0, index, 0)
def PhysicsVehicleWheelsDataAddLongSlip(builder, longSlip): builder.PrependFloat32Slot(1, longSlip, 0.0)
def PhysicsVehicleWheelsDataAddLatSlip(builder, latSlip): builder.PrependFloat32Slot(2, latSlip, 0.0)
def PhysicsVehicleWheelsDataAddNormalizedTireLoad(builder, normalizedTireLoad): builder.PrependFloat32Slot(3, normalizedTireLoad, 0.0)
def PhysicsVehicleWheelsDataAddTorque(builder, torque): builder.PrependFloat32Slot(4, torque, 0.0)
def PhysicsVehicleWheelsDataAddLongForce(builder, longForce): builder.PrependFloat32Slot(5, longForce, 0.0)
def PhysicsVehicleWheelsDataAddLatForce(builder, latForce): builder.PrependFloat32Slot(6, latForce, 0.0)
def PhysicsVehicleWheelsDataAddWheelLocation(builder, wheelLocation): builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(wheelLocation), 0)
def PhysicsVehicleWheelsDataAddWheelVelocity(builder, wheelVelocity): builder.PrependStructSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(wheelVelocity), 0)
def PhysicsVehicleWheelsDataAddSteerAngle(builder, steerAngle): builder.PrependFloat32Slot(9, steerAngle, 0.0)
def PhysicsVehicleWheelsDataAddRotationAngle(builder, rotationAngle): builder.PrependFloat32Slot(10, rotationAngle, 0.0)
def PhysicsVehicleWheelsDataAddContactMaterialName(builder, contactMaterialName): builder.PrependInt8Slot(11, contactMaterialName, 0)
def PhysicsVehicleWheelsDataAddMaxBrakeTorque(builder, maxBrakeTorque): builder.PrependFloat32Slot(12, maxBrakeTorque, 0.0)
def PhysicsVehicleWheelsDataEnd(builder): return builder.EndObject()
