# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class PhysicsVehicleActuationCommandBuffer(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPhysicsVehicleActuationCommandBuffer(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PhysicsVehicleActuationCommandBuffer()
        x.Init(buf, n + offset)
        return x

    # PhysicsVehicleActuationCommandBuffer
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PhysicsVehicleActuationCommandBuffer
    def Buffer(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # PhysicsVehicleActuationCommandBuffer
    def BufferAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # PhysicsVehicleActuationCommandBuffer
    def BufferLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def PhysicsVehicleActuationCommandBufferStart(builder): builder.StartObject(1)
def PhysicsVehicleActuationCommandBufferAddBuffer(builder, buffer): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(buffer), 0)
def PhysicsVehicleActuationCommandBufferStartBufferVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def PhysicsVehicleActuationCommandBufferEnd(builder): return builder.EndObject()
