# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class PointCloudMeasurement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPointCloudMeasurement(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PointCloudMeasurement()
        x.Init(buf, n + offset)
        return x

    # PointCloudMeasurement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PointCloudMeasurement
    def Header(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .HeaderData import HeaderData
            obj = HeaderData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Array of 3D points for sweep angles defined in the sensor profile
    # PointCloudMeasurement
    def Points(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 16
            from .PointCloudPoint import PointCloudPoint
            obj = PointCloudPoint()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PointCloudMeasurement
    def PointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def PointCloudMeasurementStart(builder): builder.StartObject(2)
def PointCloudMeasurementAddHeader(builder, header): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)
def PointCloudMeasurementAddPoints(builder, points): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(points), 0)
def PointCloudMeasurementStartPointsVector(builder, numElems): return builder.StartVector(16, numElems, 4)
def PointCloudMeasurementEnd(builder): return builder.EndObject()
