# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

# /// Used by the SDK to request advancement of simulation time
class ProxyToControlRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsProxyToControlRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProxyToControlRequest()
        x.Init(buf, n + offset)
        return x

    # ProxyToControlRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ProxyToControlRequest
    def Request(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def ProxyToControlRequestStart(builder): builder.StartObject(1)
def ProxyToControlRequestAddRequest(builder, request): builder.PrependInt8Slot(0, request, 0)
def ProxyToControlRequestEnd(builder): return builder.EndObject()
