# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class Quat4(object):
    __slots__ = ['_tab']

    # Quat4
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Quat4
    def EX(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Quat4
    def EY(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # Quat4
    def EZ(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # Quat4
    def E0(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))

def CreateQuat4(builder, eX, eY, eZ, e0):
    builder.Prep(4, 16)
    builder.PrependFloat32(e0)
    builder.PrependFloat32(eZ)
    builder.PrependFloat32(eY)
    builder.PrependFloat32(eX)
    return builder.Offset()
