# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class RadarMeasurement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsRadarMeasurement(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RadarMeasurement()
        x.Init(buf, n + offset)
        return x

    # RadarMeasurement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RadarMeasurement
    def Header(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .HeaderData import HeaderData
            obj = HeaderData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Array of objects, one for each detected by radar
    # RadarMeasurement
    def RadarSensor(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 28
            from .RadarObject import RadarObject
            obj = RadarObject()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RadarMeasurement
    def RadarSensorLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def RadarMeasurementStart(builder): builder.StartObject(2)
def RadarMeasurementAddHeader(builder, header): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)
def RadarMeasurementAddRadarSensor(builder, radarSensor): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(radarSensor), 0)
def RadarMeasurementStartRadarSensorVector(builder, numElems): return builder.StartVector(28, numElems, 4)
def RadarMeasurementEnd(builder): return builder.EndObject()
