# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

class RadarObjectStatus(object):
# /// Object is new
    NEW = 0
# /// Update for a previously tracked object
    TRACKED = 1

