# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class RadarObject(object):
    __slots__ = ['_tab']

    # RadarObject
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

# /// Yaw angle to the object (deg)
    # RadarObject
    def Yaw(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
# /// Distance (m)
    # RadarObject
    def Range(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
# /// Return signal power (dB)
    # RadarObject
    def PowerDb(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
# /// Rate of change of range (m/s)
    # RadarObject
    def RangeRate(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
# /// Lateral rate of change (rad)
    # RadarObject
    def LatRate(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
# /// Stable ID for persistent tracking
    # RadarObject
    def Id(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(20))
# /// Whether this is a new object or previously tracked
    # RadarObject
    def Status(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(24))

def CreateRadarObject(builder, yaw, range, powerDb, rangeRate, latRate, id, status):
    builder.Prep(4, 28)
    builder.Pad(3)
    builder.PrependInt8(status)
    builder.PrependInt32(id)
    builder.PrependFloat32(latRate)
    builder.PrependFloat32(rangeRate)
    builder.PrependFloat32(powerDb)
    builder.PrependFloat32(range)
    builder.PrependFloat32(yaw)
    return builder.Offset()
