# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

# /// This message is primarily used between the engine's internal systems. For controlling
# /// frame advance with the SDK, see ControlToProxyReply.
class SimControlReply(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSimControlReply(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SimControlReply()
        x.Init(buf, n + offset)
        return x

    # SimControlReply
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SimControlReply
    def Reply(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def SimControlReplyStart(builder): builder.StartObject(1)
def SimControlReplyAddReply(builder, reply): builder.PrependInt8Slot(0, reply, 0)
def SimControlReplyEnd(builder): return builder.EndObject()
