# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

# /// This message is primarily used between the engine's internal systems. For controlling
# /// frame advance with the SDK, see ProxyToControlRequest.
class SimControlRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSimControlRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SimControlRequest()
        x.Init(buf, n + offset)
        return x

    # SimControlRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SimControlRequest
    def Request(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # SimControlRequest
    def SimTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def SimControlRequestStart(builder): builder.StartObject(2)
def SimControlRequestAddRequest(builder, request): builder.PrependInt8Slot(0, request, 0)
def SimControlRequestAddSimTime(builder, simTime): builder.PrependFloat64Slot(1, simTime, 0.0)
def SimControlRequestEnd(builder): return builder.EndObject()
