# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

# /// Request change in simulation state
class SimStateRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSimStateRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SimStateRequest()
        x.Init(buf, n + offset)
        return x

    # SimStateRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SimStateRequest
    def Command(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def SimStateRequestStart(builder): builder.StartObject(1)
def SimStateRequestAddCommand(builder, command): builder.PrependInt8Slot(0, command, 0)
def SimStateRequestEnd(builder): return builder.EndObject()
