# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

# /// Reply for SimStateRequest command
class SimStateReply(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSimStateReply(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SimStateReply()
        x.Init(buf, n + offset)
        return x

    # SimStateReply
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SimStateReply
    def State(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # SimStateReply
    def Time(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def SimStateReplyStart(builder): builder.StartObject(2)
def SimStateReplyAddState(builder, state): builder.PrependInt8Slot(0, state, 0)
def SimStateReplyAddTime(builder, time): builder.PrependFloat64Slot(1, time, 0.0)
def SimStateReplyEnd(builder): return builder.EndObject()
