# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

# /// Snap To Ground input/output positions. (same schema for both request & reply)
class SnapToGround(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSnapToGround(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SnapToGround()
        x.Init(buf, n + offset)
        return x

    # SnapToGround
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SnapToGround
    def Positions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SnapToGround
    def PositionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def SnapToGroundStart(builder): builder.StartObject(1)
def SnapToGroundAddPositions(builder, positions): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(positions), 0)
def SnapToGroundStartPositionsVector(builder, numElems): return builder.StartVector(12, numElems, 4)
def SnapToGroundEnd(builder): return builder.EndObject()
