# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

# /// List of states changes from an origin
class StateEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsStateEvent(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StateEvent()
        x.Init(buf, n + offset)
        return x

    # StateEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StateEvent
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

    # StateEvent
    def States(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .StateInteraction import StateInteraction
            obj = StateInteraction()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StateEvent
    def StatesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def StateEventStart(builder): builder.StartObject(2)
def StateEventAddId(builder, id): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)
def StateEventAddStates(builder, states): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(states), 0)
def StateEventStartStatesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StateEventEnd(builder): return builder.EndObject()
