# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

# /// Capturing the state of interaction
class StateInteraction(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsStateInteraction(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StateInteraction()
        x.Init(buf, n + offset)
        return x

    # StateInteraction
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StateInteraction
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

    # StateInteraction
    def Properties(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .StateProperty import StateProperty
            obj = StateProperty()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StateInteraction
    def PropertiesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def StateInteractionStart(builder): builder.StartObject(2)
def StateInteractionAddId(builder, id): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)
def StateInteractionAddProperties(builder, properties): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(properties), 0)
def StateInteractionStartPropertiesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StateInteractionEnd(builder): return builder.EndObject()
