# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class TeleportRequest(object):
    __slots__ = ['_tab']

    # TeleportRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

# /// World space offset (m) from the East-North-Up origin
    # TeleportRequest
    def Location(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

# /// World space rotation (rad) relative to East-North-Up axis
    # TeleportRequest
    def Orientation(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 12)
        return obj

# /// Object space velocity (m/s)
    # TeleportRequest
    def Velocity(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 28)
        return obj

# /// Object space angular velocity (rad/s)
    # TeleportRequest
    def AngularVelocity(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 40)
        return obj


def CreateTeleportRequest(builder, location_x, location_y, location_z, orientation_eX, orientation_eY, orientation_eZ, orientation_e0, velocity_x, velocity_y, velocity_z, angular_velocity_x, angular_velocity_y, angular_velocity_z):
    builder.Prep(4, 52)
    builder.Prep(4, 12)
    builder.PrependFloat32(angular_velocity_z)
    builder.PrependFloat32(angular_velocity_y)
    builder.PrependFloat32(angular_velocity_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(velocity_z)
    builder.PrependFloat32(velocity_y)
    builder.PrependFloat32(velocity_x)
    builder.Prep(4, 16)
    builder.PrependFloat32(orientation_e0)
    builder.PrependFloat32(orientation_eZ)
    builder.PrependFloat32(orientation_eY)
    builder.PrependFloat32(orientation_eX)
    builder.Prep(4, 12)
    builder.PrependFloat32(location_z)
    builder.PrependFloat32(location_y)
    builder.PrependFloat32(location_x)
    return builder.Offset()
