# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

class TrafficSignalState(object):
    off = 1
    red = 2
    yellow = 3
    green = 4
    red_left = 5
    yellow_left = 6
    green_left = 7
    red_right = 8
    yellow_right = 9
    green_right = 10
    red_up = 11
    yellow_up = 12
    green_up = 13
    red_flashing = 14
    yellow_flashing = 15

