# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class TrafficSignals(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTrafficSignals(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrafficSignals()
        x.Init(buf, n + offset)
        return x

    # TrafficSignals
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TrafficSignals
    def Header(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .HeaderData import HeaderData
            obj = HeaderData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrafficSignals
    def Names(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # TrafficSignals
    def NamesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TrafficSignals
    def States(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # TrafficSignals
    def StatesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # TrafficSignals
    def StatesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def TrafficSignalsStart(builder): builder.StartObject(3)
def TrafficSignalsAddHeader(builder, header): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)
def TrafficSignalsAddNames(builder, names): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(names), 0)
def TrafficSignalsStartNamesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def TrafficSignalsAddStates(builder, states): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(states), 0)
def TrafficSignalsStartStatesVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def TrafficSignalsEnd(builder): return builder.EndObject()
