# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

class TriggerInteractionType(object):
# /// physically exiting the trigger volume, or no longer satisfying the logic condition(s)
    DEACTIVATION = 0
# /// physically entering the trigger volume, or initial satisfaction of the logic condition(s)
    ACTIVATION = 1

