# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

# /// Dynamic state of a trigger
class TriggerState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTriggerState(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TriggerState()
        x.Init(buf, n + offset)
        return x

    # TriggerState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TriggerState
    def TriggerUuid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .UUID import UUID
            obj = UUID()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TriggerState
    def Location(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TriggerState
    def Orientation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from .Quat4 import Quat4
            obj = Quat4()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def TriggerStateStart(builder): builder.StartObject(3)
def TriggerStateAddTriggerUuid(builder, triggerUuid): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(triggerUuid), 0)
def TriggerStateAddLocation(builder, location): builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(location), 0)
def TriggerStateAddOrientation(builder, orientation): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(orientation), 0)
def TriggerStateEnd(builder): return builder.EndObject()
