# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

# /// List of object UUIDs that have activated/deactivated a trigger this frame
class TriggerEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTriggerEvent(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TriggerEvent()
        x.Init(buf, n + offset)
        return x

    # TriggerEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TriggerEvent
    def TriggerUuid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .UUID import UUID
            obj = UUID()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TriggerEvent
    def Interactions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .TriggerInteraction import TriggerInteraction
            obj = TriggerInteraction()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TriggerEvent
    def InteractionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def TriggerEventStart(builder): builder.StartObject(2)
def TriggerEventAddTriggerUuid(builder, triggerUuid): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(triggerUuid), 0)
def TriggerEventAddInteractions(builder, interactions): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(interactions), 0)
def TriggerEventStartInteractionsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def TriggerEventEnd(builder): return builder.EndObject()
