# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

# /// When an activator has either activated or deactivated a trigger
# /// Note that for each activator, there is a single activation and a single deactivation
class TriggerInteraction(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTriggerInteraction(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TriggerInteraction()
        x.Init(buf, n + offset)
        return x

    # TriggerInteraction
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TriggerInteraction
    def ActivatorUuid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .UUID import UUID
            obj = UUID()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TriggerInteraction
    def InteractionType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def TriggerInteractionStart(builder): builder.StartObject(2)
def TriggerInteractionAddActivatorUuid(builder, activatorUuid): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(activatorUuid), 0)
def TriggerInteractionAddInteractionType(builder, interactionType): builder.PrependInt8Slot(1, interactionType, 0)
def TriggerInteractionEnd(builder): return builder.EndObject()
