# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class UltrasonicMeasurement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsUltrasonicMeasurement(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UltrasonicMeasurement()
        x.Init(buf, n + offset)
        return x

    # UltrasonicMeasurement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UltrasonicMeasurement
    def Header(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .HeaderData import HeaderData
            obj = HeaderData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Range (m) when an object is detected, FLT_MAX otherwise
    # UltrasonicMeasurement
    def Range(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// True if the distance falls into range of the sensor and range is valid
    # UltrasonicMeasurement
    def Valid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos)
        return 0

def UltrasonicMeasurementStart(builder): builder.StartObject(3)
def UltrasonicMeasurementAddHeader(builder, header): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)
def UltrasonicMeasurementAddRange(builder, range): builder.PrependFloat32Slot(1, range, 0.0)
def UltrasonicMeasurementAddValid(builder, valid): builder.PrependBoolSlot(2, valid, 0)
def UltrasonicMeasurementEnd(builder): return builder.EndObject()
