# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class UUID(object):
    __slots__ = ['_tab']

    # UUID
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UUID
    def A(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # UUID
    def B(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # UUID
    def C(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # UUID
    def D(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))

def CreateUUID(builder, a, b, c, d):
    builder.Prep(4, 16)
    builder.PrependUint32(d)
    builder.PrependUint32(c)
    builder.PrependUint32(b)
    builder.PrependUint32(a)
    return builder.Offset()
