# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class VehicleDashboard(object):
    __slots__ = ['_tab']

    # VehicleDashboard
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

# /// current state of VI-CRT solver
    # VehicleDashboard
    def VicrtState(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
# /// steering wheel angle in degrees (clockwise is positive)
    # VehicleDashboard
    def Steering(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
# /// throttle pedal
    # VehicleDashboard
    def Throttle(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
# /// brake pedal
    # VehicleDashboard
    def Brake(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
# /// engine rpm
    # VehicleDashboard
    def Rpm(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
# /// current gear of transmission
    # VehicleDashboard
    def Gear(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(20))

def CreateVehicleDashboard(builder, vicrtState, steering, throttle, brake, rpm, gear):
    builder.Prep(4, 24)
    builder.PrependInt32(gear)
    builder.PrependFloat32(rpm)
    builder.PrependFloat32(brake)
    builder.PrependFloat32(throttle)
    builder.PrependFloat32(steering)
    builder.Pad(3)
    builder.PrependInt8(vicrtState)
    return builder.Offset()
