# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class VehicleControlIntent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsVehicleControlIntent(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VehicleControlIntent()
        x.Init(buf, n + offset)
        return x

    # VehicleControlIntent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

# /// Acceleration (m/s^2)
    # VehicleControlIntent
    def Acceleration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Speed (m/s)
    # VehicleControlIntent
    def DesiredSpeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Curvature of the road ahead for steering (radians, positive counterclockwise)
    # VehicleControlIntent
    def CurvatureOverall(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

# /// Where the vehicle expects it will be in 0.5 seconds.
    # VehicleControlIntent
    def LocInHalfSec(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Where the vehicle expects it will be in 1.0 seconds.
    # VehicleControlIntent
    def LocInOneSec(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def VehicleControlIntentStart(builder): builder.StartObject(5)
def VehicleControlIntentAddAcceleration(builder, acceleration): builder.PrependFloat32Slot(0, acceleration, 0.0)
def VehicleControlIntentAddDesiredSpeed(builder, desiredSpeed): builder.PrependFloat32Slot(1, desiredSpeed, 0.0)
def VehicleControlIntentAddCurvatureOverall(builder, curvatureOverall): builder.PrependFloat32Slot(2, curvatureOverall, 0.0)
def VehicleControlIntentAddLocInHalfSec(builder, locInHalfSec): builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(locInHalfSec), 0)
def VehicleControlIntentAddLocInOneSec(builder, locInOneSec): builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(locInOneSec), 0)
def VehicleControlIntentEnd(builder): return builder.EndObject()
