# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class VehicleFeatures(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsVehicleFeatures(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VehicleFeatures()
        x.Init(buf, n + offset)
        return x

    # VehicleFeatures
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

# /// When enabled, headlights will automatically correct pitch and yaw with steering
    # VehicleFeatures
    def AdaptiveHeadlights(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos)
        return 0

def VehicleFeaturesStart(builder): builder.StartObject(1)
def VehicleFeaturesAddAdaptiveHeadlights(builder, adaptiveHeadlights): builder.PrependBoolSlot(0, adaptiveHeadlights, 0)
def VehicleFeaturesEnd(builder): return builder.EndObject()
