# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class VehicleLights(object):
    __slots__ = ['_tab']

    # VehicleLights
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

# /// angle for steerable headlights (deprecated, do not use)
    # VehicleLights
    def HeadlightAngleDegreesDeprecated(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
# /// low beam headlights on the left
    # VehicleLights
    def LowBeamLeft(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
# /// low beam headlights on the right
    # VehicleLights
    def LowBeamRight(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(5))
# /// high beam headlights on the left
    # VehicleLights
    def HighBeamLeft(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(6))
# /// high beam headlights on the right
    # VehicleLights
    def HighBeamRight(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(7))
# /// left turn signal (could be split front/rear/side if needed)
    # VehicleLights
    def TurnSignalLeft(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
# /// left turn signal (could be split front/rear/side if needed)
    # VehicleLights
    def TurnSignalRight(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(9))
# /// left fog light (for vehicles that have them)
    # VehicleLights
    def FogLightLeft(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(10))
# /// right fog light (for vehicles that have them)
    # VehicleLights
    def FogLightRight(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(11))
# /// left tail light (should be triggered along with low beams or for "parking" lights)
    # VehicleLights
    def TailLightLeft(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
# /// right tail light (should be triggered along with low beams or for "parking" lights)
    # VehicleLights
    def TailLightRight(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(13))
# /// higher intensity left tail light for braking
    # VehicleLights
    def BrakeLightLeft(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(14))
# /// higher intensity right tail light for braking
    # VehicleLights
    def BrakeLightRight(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(15))
# /// CHMSL light for braking
    # VehicleLights
    def BrakeLightCenter(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
# /// reverse lights
    # VehicleLights
    def ReverseLamps(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(17))
# /// parking lights
    # VehicleLights
    def ParkingLamps(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(18))
# /// accent lights, etc. (we are also currently using for police/ambulance lights but should separate)
    # VehicleLights
    def DaytimeRunningLamps(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(19))

def CreateVehicleLights(builder, headlightAngleDegreesDeprecated, lowBeamLeft, lowBeamRight, highBeamLeft, highBeamRight, turnSignalLeft, turnSignalRight, fogLightLeft, fogLightRight, tailLightLeft, tailLightRight, brakeLightLeft, brakeLightRight, brakeLightCenter, reverseLamps, parkingLamps, daytimeRunningLamps):
    builder.Prep(4, 20)
    builder.PrependBool(daytimeRunningLamps)
    builder.PrependBool(parkingLamps)
    builder.PrependBool(reverseLamps)
    builder.PrependBool(brakeLightCenter)
    builder.PrependBool(brakeLightRight)
    builder.PrependBool(brakeLightLeft)
    builder.PrependBool(tailLightRight)
    builder.PrependBool(tailLightLeft)
    builder.PrependBool(fogLightRight)
    builder.PrependBool(fogLightLeft)
    builder.PrependBool(turnSignalRight)
    builder.PrependBool(turnSignalLeft)
    builder.PrependBool(highBeamRight)
    builder.PrependBool(highBeamLeft)
    builder.PrependBool(lowBeamRight)
    builder.PrependBool(lowBeamLeft)
    builder.PrependFloat32(headlightAngleDegreesDeprecated)
    return builder.Offset()
