# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

import flatbuffers

class VirtualSensorMeasurement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsVirtualSensorMeasurement(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VirtualSensorMeasurement()
        x.Init(buf, n + offset)
        return x

    # VirtualSensorMeasurement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VirtualSensorMeasurement
    def Header(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .HeaderData import HeaderData
            obj = HeaderData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

# /// Lane marking data ordered along Y axis (right to left)
    # VirtualSensorMeasurement
    def LaneMarkings(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .LaneMarking import LaneMarking
            obj = LaneMarking()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VirtualSensorMeasurement
    def LaneMarkingsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

# /// Signs and other point feature data types from map
    # VirtualSensorMeasurement
    def MapObjects(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .ObjData import ObjData
            obj = ObjData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VirtualSensorMeasurement
    def MapObjectsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

# /// scenario objects (agents and static obstacles) 
    # VirtualSensorMeasurement
    def Obstacles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .ObjData import ObjData
            obj = ObjData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VirtualSensorMeasurement
    def ObstaclesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def VirtualSensorMeasurementStart(builder): builder.StartObject(4)
def VirtualSensorMeasurementAddHeader(builder, header): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)
def VirtualSensorMeasurementAddLaneMarkings(builder, laneMarkings): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(laneMarkings), 0)
def VirtualSensorMeasurementStartLaneMarkingsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def VirtualSensorMeasurementAddMapObjects(builder, mapObjects): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(mapObjects), 0)
def VirtualSensorMeasurementStartMapObjectsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def VirtualSensorMeasurementAddObstacles(builder, obstacles): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(obstacles), 0)
def VirtualSensorMeasurementStartObstaclesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def VirtualSensorMeasurementEnd(builder): return builder.EndObject()
