# automatically generated by the FlatBuffers compiler, do not modify

# namespace: RHMsg

class WheelContactMaterial(object):
    UNKNOWN = 0
    ROAD = 1
    PAINTED = 2
    SIDEWALK = 3
    METAL = 4
    GRASS = 5
    DIRTROAD = 6
    NONE = 255

